apiVersion: v1
kind: Namespace
metadata:
  name: zamannegar-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: zamannegar-ns
data:
  # In a real K8s cluster, this would be your Ingress domain (e.g., https://api.zamannegar.com)
  # For local testing (Minikube), it might still be localhost mapped via NodePort
  NEXT_PUBLIC_API_URL: "http://localhost:8000"
  POSTGRES_DB: "zamannegar"
  POSTGRES_HOST: "postgres-service"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: zamannegar-ns
type: Opaque
stringData:
  POSTGRES_USER: "zaman_admin"
  POSTGRES_PASSWORD: "secure_password_2025"
  SECRET_KEY: "change_this_to_a_real_random_string_in_production"
---
# --- DATABASE (Postgres 18) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: zamannegar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          # Using Postgres 18 (Released Late 2025)
          image: postgres:18-alpine
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "zaman_admin"]
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: zamannegar-ns
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
---
# --- BACKEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: zamannegar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: zaman-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              # Construct the connection string dynamically
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/$(POSTGRES_DB)"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            # Load these individually to build the string above
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: zamannegar-ns
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
# --- FRONTEND ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: zamannegar-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: zaman-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEXT_PUBLIC_API_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: zamannegar-ns
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000